"""Canonical content blueprint for the standalone CodeQuest Academy curriculum.

The blueprint deliberately keeps educational decisions separate from JSON generation.
Each lesson topic has a distinct title and a precise principle that downstream builders
turn into interactive explanations, examples, practices, challenges, and assessments.
"""

from __future__ import annotations


TRACKS = [
    {
        "id": "web_development",
        "title": "Web Development",
        "paths": ["frontend_web_development", "backend_web_development"],
    },
    {
        "id": "app_development",
        "title": "App Development",
        "paths": ["flutter_development", "react_native_development"],
    },
    {
        "id": "cybersecurity",
        "title": "Cybersecurity",
        "paths": ["security_fundamentals", "ethical_hacking"],
    },
    {
        "id": "problem_solving",
        "title": "Problem Solving",
        "paths": ["data_structures", "algorithms_coding_interviews"],
    },
    {
        "id": "ai_machine_learning",
        "title": "AI and Machine Learning",
        "paths": ["machine_learning_fundamentals", "nlp_ai"],
    },
]


PATHS = {
    "frontend_web_development": {
        "title": "Frontend Web Development",
        "track_id": "web_development",
        "prefix": "FE",
        "context": "an accessible browser interface",
        "representation": "a document tree, layout constraints, and user-driven state transitions",
        "artifact": "responsive web application",
        "runtime": "javascript",
    },
    "backend_web_development": {
        "title": "Backend Web Development",
        "track_id": "web_development",
        "prefix": "BE",
        "context": "a reliable request-processing service",
        "representation": "pipelines, records, relations, and trust boundaries",
        "artifact": "production-style API service",
        "runtime": "javascript",
    },
    "flutter_development": {
        "title": "Flutter Development",
        "track_id": "app_development",
        "prefix": "FLUT",
        "context": "a cross-platform mobile experience",
        "representation": "widget trees, constraints, navigation graphs, and state transitions",
        "artifact": "Flutter mobile application",
        "runtime": "unsupported_dart",
    },
    "react_native_development": {
        "title": "React Native Development",
        "track_id": "app_development",
        "prefix": "RN",
        "context": "a native-feeling cross-platform experience",
        "representation": "component trees, navigation graphs, event flows, and asynchronous timelines",
        "artifact": "React Native mobile application",
        "runtime": "javascript",
    },
    "security_fundamentals": {
        "title": "Security Fundamentals",
        "track_id": "cybersecurity",
        "prefix": "SEC",
        "context": "the fictional Northstar Learning Lab",
        "representation": "assets, threats, vulnerabilities, controls, logs, and trust boundaries",
        "artifact": "defensive security improvement portfolio",
        "runtime": "structural_only",
        "safety": "defensive, fictional, authorization-first, and isolated-lab-only",
    },
    "ethical_hacking": {
        "title": "Ethical Hacking",
        "track_id": "cybersecurity",
        "prefix": "HACK",
        "context": "the isolated and fictional Aurora Practice Range",
        "representation": "written scope, evidence chains, safe validation, risk ratings, and remediation",
        "artifact": "authorized assessment report for a fictional lab",
        "runtime": "structural_only",
        "safety": "defensive, fictional, authorization-first, and isolated-lab-only",
    },
    "data_structures": {
        "title": "Data Structures",
        "track_id": "problem_solving",
        "prefix": "DS",
        "context": "a constrained data-processing problem",
        "representation": "states, operations, invariants, diagrams, and complexity bounds",
        "artifact": "data-structure reasoning portfolio",
        "runtime": "javascript",
    },
    "algorithms_coding_interviews": {
        "title": "Algorithms and Coding Interviews",
        "track_id": "problem_solving",
        "prefix": "AL",
        "context": "a timed but explainable problem-solving scenario",
        "representation": "input-output contracts, invariants, trace tables, and complexity comparisons",
        "artifact": "interview-ready algorithm solution set",
        "runtime": "javascript",
    },
    "machine_learning_fundamentals": {
        "title": "Machine Learning Fundamentals",
        "track_id": "ai_machine_learning",
        "prefix": "ML",
        "context": "a small, documented prediction system",
        "representation": "vectors, matrices, distributions, functions, losses, and error costs",
        "artifact": "responsible machine-learning model card and prototype",
        "runtime": "structural_only",
    },
    "nlp_ai": {
        "title": "Natural Language Processing and AI",
        "track_id": "ai_machine_learning",
        "prefix": "AI",
        "context": "a bounded language-assistance system",
        "representation": "tokens, vectors, weighted relationships, retrieval records, and evaluation sets",
        "artifact": "evaluated and safety-bounded NLP application",
        "runtime": "structural_only",
    },
}


def T(title: str, principle: str) -> dict:
    return {"title": title, "principle": principle}


LEVELS = [
    # Frontend Web Development
    {
        "path_id": "frontend_web_development", "code": "FE-101", "number": 1,
        "title": "Web and HTML Foundations",
        "topics": [
            T("Web requests and browser rendering", "A URL identifies a resource; the browser requests it, interprets the response, builds internal trees, and renders pixels."),
            T("Semantic document skeleton", "A valid page separates metadata from visible content and uses landmarks that communicate each region's purpose."),
            T("Nesting and the document tree", "HTML elements form a rooted tree: every non-root node has one parent, and correct nesting preserves the intended hierarchy."),
            T("Text, links, images, and paths", "Content elements carry meaning, while relative and absolute paths determine how a browser locates linked resources."),
            T("Lists, tables, and structured records", "Choose lists for sequences and tables for genuinely two-dimensional relationships with explicit headers."),
            T("Forms as input-output contracts", "A form maps labeled user inputs to named values, applies constraints, and submits a predictable record."),
            T("Accessible HTML and keyboard flow", "Names, roles, relationships, focus order, and alternatives make the same structure perceivable without relying on sight or a pointer."),
            T("Validation, debugging, and static publishing", "Debug from document structure outward: validate markup, inspect paths, test interaction order, then verify the deployed response."),
        ],
    },
    {
        "path_id": "frontend_web_development", "code": "FE-201", "number": 2,
        "title": "Modern CSS and Responsive Design",
        "topics": [
            T("Cascade, specificity, and inheritance", "The winning declaration is determined by origin, importance, specificity, and source order; only inheritable properties flow from parent to child."),
            T("Box model and predictable sizing", "Rendered size is the sum of content, padding, border, and margin unless border-box sizing moves padding and border inside the declared dimensions."),
            T("Selectors, combinators, and UI states", "Selectors describe sets of nodes and relationships; narrowly target stable structure without encoding accidental nesting."),
            T("Normal flow, display, and positioning", "Normal flow places boxes in document order; positioning should change a box's reference relationship only when the design requires it."),
            T("Flexbox axes and alignment", "Flexbox distributes items along one main axis and aligns them along the cross axis under available-space constraints."),
            T("Grid tracks and two-dimensional layout", "Grid defines row and column tracks, then places items into cells or named regions while preserving explicit spatial relationships."),
            T("Responsive constraints and media queries", "Responsive design selects fluid defaults and introduces breakpoints where content constraints—not device names—stop being satisfied."),
            T("Design tokens, accessibility, and CSS debugging", "Reusable tokens keep visual relationships consistent; contrast, focus, zoom, and inspector checks protect usability across states."),
        ],
    },
    {
        "path_id": "frontend_web_development", "code": "FE-301", "number": 3,
        "title": "JavaScript and Programming Logic",
        "topics": [
            T("Values, types, and explicit conversion", "A value has a type that determines valid operations; explicit conversion makes input assumptions visible and testable."),
            T("Variables, expressions, and state", "A variable names a current value, while an expression maps existing values to a new result without changing unrelated state."),
            T("Boolean logic and branching", "A branch partitions possible states by predicates; conditions must be mutually understood and boundary cases tested."),
            T("Loops, counters, and invariants", "A loop needs an initial state, continuation condition, update, and invariant that remains true after every iteration."),
            T("Functions as input-output mappings", "A function defines a reusable contract from parameters to a return value or documented effect, with scope limiting accidental dependencies."),
            T("Arrays and sequence transformations", "Arrays model ordered data; map, filter, find, and reduce express distinct transformations with predictable output shapes."),
            T("Objects, records, and lookup", "Objects group named fields into records; safe access and deliberate updates preserve the record's expected shape."),
            T("DOM events and interface state", "An event supplies input, a handler computes a state transition, and rendering makes the new state visible in the document tree."),
        ],
    },
    {
        "path_id": "frontend_web_development", "code": "FE-401", "number": 4,
        "title": "Advanced JavaScript, APIs and Browser Data",
        "topics": [
            T("Asynchronous timelines and promises", "A promise represents a future result; awaiting it orders dependent work without blocking unrelated browser tasks."),
            T("Fetch and HTTP response handling", "A network request is not complete at receipt: code must inspect status, parse the expected body, and handle transport and application failures separately."),
            T("JSON contracts and defensive parsing", "External JSON is untrusted structured data; validate required fields and types before allowing it to update application state."),
            T("Failures, retries, and user-visible states", "Loading, success, empty, and failure are distinct states; retries must be bounded and safe for the operation being repeated."),
            T("Browser storage and data lifetime", "Choose memory, session, or persistent storage by lifetime, sensitivity, capacity, and synchronization needs."),
            T("Modules and dependency boundaries", "Modules expose small public contracts and hide internal details, producing a directed dependency graph that is easier to test."),
            T("Functional transformations and immutability", "Non-mutating transformations create a new value from old state, making change histories and UI updates easier to reason about."),
            T("API-driven application architecture", "Separate transport, validation, domain state, and rendering so each layer has one responsibility and failures stay localized."),
        ],
    },
    {
        "path_id": "frontend_web_development", "code": "FE-501", "number": 5,
        "title": "React, Architecture, Testing and Deployment",
        "topics": [
            T("Components, JSX, and render trees", "A component maps inputs and current state to a declarative subtree; composition builds the full interface tree."),
            T("Props, contracts, and composition", "Props are read-only inputs; clear prop contracts and composition keep parent-child responsibilities explicit."),
            T("State, identity, and render transitions", "State belongs at the nearest common owner, and stable identity determines whether React preserves or replaces a component's state."),
            T("Events, controlled forms, and reducers", "User events become actions; controlled values or reducers make each transition from previous state to next state explicit."),
            T("Effects and synchronized external systems", "An effect synchronizes rendering with an external system and needs accurate dependencies plus cleanup for obsolete work."),
            T("Routing and shared application state", "Routes form a navigation graph; only genuinely shared state should move above local component boundaries."),
            T("Testing, accessibility, and performance", "Test observable behavior, measure before optimizing, and preserve accessible names, focus, and feedback across every state."),
            T("Build, deployment, and maintainable architecture", "A deployable frontend has reproducible builds, environment separation, monitored assets, and clear layer boundaries."),
        ],
    },

    # Backend Web Development
    {
        "path_id": "backend_web_development", "code": "BE-101", "number": 1,
        "title": "Backend Systems, HTTP and Node.js Foundations",
        "topics": [
            T("Client-server boundaries", "A client requests a capability; a server validates the request, performs controlled work, and returns a documented response."),
            T("HTTP methods and resource intent", "Methods communicate intent: retrieval, creation, replacement, partial change, and deletion have different safety and idempotency properties."),
            T("URLs, headers, bodies, and status codes", "An HTTP message combines routing data, metadata, optional content, and a status that summarizes the outcome."),
            T("Node.js modules and runtime state", "A Node process loads modules into a dependency graph and keeps process-wide state separate from request-specific values."),
            T("Event loop and asynchronous I/O", "The event loop schedules callbacks after I/O completes; CPU-heavy work blocks progress while pending I/O does not."),
            T("Configuration, files, and environment values", "Configuration varies by environment and belongs outside source code; paths and failures must be handled explicitly."),
            T("Building a minimal request pipeline", "A server pipeline parses a request, routes it, performs domain work, and serializes one response exactly once."),
            T("Errors, logging, and graceful shutdown", "Operational errors need structured context, safe client messages, and orderly resource cleanup during shutdown."),
        ],
    },
    {
        "path_id": "backend_web_development", "code": "BE-201", "number": 2,
        "title": "Express, Routing, Middleware and Validation",
        "topics": [
            T("Express applications and routers", "Routers partition the URL-method space into cohesive resource contracts instead of one growing conditional chain."),
            T("Path parameters, queries, and bodies", "Use path values for identity, query values for optional views, and bodies for structured commands or resource data."),
            T("Middleware as ordered transformations", "Middleware is an ordered pipeline; each stage either terminates the response or passes a well-defined request state forward."),
            T("Validation and normalization", "Validate shape and constraints at the boundary, then normalize accepted data into one internal representation."),
            T("Central error handling", "Domain, validation, and infrastructure failures map to stable error responses without exposing internal secrets."),
            T("REST resource modeling", "Resources use stable nouns, consistent representations, and predictable method semantics across collections and members."),
            T("CORS, security headers, and rate decisions", "Browser trust rules, protective headers, and fair-use limits reduce risk when configured for explicit origins and operations."),
            T("Route tests and contract verification", "Route tests control dependencies and assert status, headers, response shape, and side effects at meaningful boundaries."),
        ],
    },
    {
        "path_id": "backend_web_development", "code": "BE-301", "number": 3,
        "title": "Databases, SQL, Data Modeling and Queries",
        "topics": [
            T("Relations, rows, columns, and keys", "A relational table represents a set of similarly shaped facts; keys identify rows and connect related sets."),
            T("Entities, cardinality, and ER models", "Cardinality states how many records may relate, determining whether a foreign key or junction table represents the relationship."),
            T("Selecting, filtering, and ordering", "A query transforms a relation by choosing columns, retaining rows that satisfy predicates, and applying order only when requested."),
            T("Joins and set relationships", "A join pairs rows according to a predicate; join type determines which unmatched rows remain in the result."),
            T("Aggregation and grouping", "Grouping partitions rows by keys, then aggregate functions reduce each group to summary values."),
            T("Writes, constraints, and transactions", "A transaction moves the database from one valid state to another atomically while constraints guard invariants."),
            T("Indexes and query plans", "An index trades write cost and storage for faster ordered lookup; the query plan reveals whether that trade is being used."),
            T("Normalization and schema migrations", "Normalization reduces contradictory facts, while versioned migrations change schema and data in controlled, reversible steps."),
        ],
    },
    {
        "path_id": "backend_web_development", "code": "BE-401", "number": 4,
        "title": "Authentication, Authorization and Application Security",
        "topics": [
            T("Password storage and verification", "Store salted slow password hashes, compare them safely, and never retain or log the original secret."),
            T("Sessions, tokens, and expiration", "A credential binds an authenticated identity to a limited lifetime and scope; revocation and storage choices change the risk."),
            T("Authentication versus authorization", "Authentication establishes who is acting; authorization evaluates whether that actor may perform this action on this resource."),
            T("Cookies, CSRF, and browser sessions", "Secure cookie attributes protect transport and script access, while CSRF defenses ensure a state-changing request reflects user intent."),
            T("Injection prevention and boundary validation", "Treat external data as data, not executable syntax; parameterization and allowlisted validation preserve that boundary."),
            T("Secrets and environment isolation", "Secrets need restricted storage, rotation, least privilege, and separation from source, logs, and client-visible bundles."),
            T("Audit events and privacy-aware logging", "Audit logs record security-relevant who-what-when outcomes while minimizing sensitive content and protecting integrity."),
            T("Threat modeling and layered controls", "Map assets, entry points, trust boundaries, threats, and mitigations so multiple controls reduce both likelihood and impact."),
        ],
    },
    {
        "path_id": "backend_web_development", "code": "BE-501", "number": 5,
        "title": "Production APIs, Testing, Deployment and Scaling",
        "topics": [
            T("Versioning, pagination, and compatibility", "Evolve contracts deliberately; pagination bounds work, and compatibility rules prevent existing clients from breaking unexpectedly."),
            T("Testing pyramid and controlled dependencies", "Use many fast unit tests, focused integration tests, and a small number of end-to-end tests around the highest-risk journeys."),
            T("Observability with logs, metrics, and traces", "Logs explain events, metrics reveal aggregate behavior, and traces connect work across a distributed request path."),
            T("Caching and invalidation", "A cache is a derived copy with a freshness policy; keys, lifetime, invalidation, and failure behavior determine correctness."),
            T("Queues and background jobs", "A queue separates arrival from processing; acknowledgments, retries, dead-letter handling, and idempotency prevent silent loss or duplicate harm."),
            T("Concurrency and idempotent operations", "Concurrent requests can interleave; atomic constraints and idempotency keys protect shared-state invariants."),
            T("Containers, deployment, and health checks", "A deployable service has reproducible artifacts, explicit configuration, health signals, migrations, and safe rollout/rollback steps."),
            T("Scaling, reliability, and capacity", "Capacity planning connects arrival rate, service time, utilization, latency, redundancy, and recovery objectives."),
        ],
    },

    # Flutter Development
    {
        "path_id": "flutter_development", "code": "FLUT-101", "number": 1,
        "title": "Dart and Flutter Foundations",
        "topics": [
            T("Dart values, types, and null safety", "Types describe valid operations, while nullable and non-nullable references make absence an explicit part of the contract."),
            T("Variables, expressions, and functions", "Functions map typed parameters to results or documented effects, and local variables keep intermediate state bounded."),
            T("Conditions, loops, and exhaustive cases", "Control flow partitions states or repeats a transition; every branch and termination boundary must be accounted for."),
            T("Lists, maps, and immutable transformations", "Collections encode order or key lookup; creating transformed values makes state changes easier to trace."),
            T("Futures, async, and event timelines", "A Future represents one eventual result, and await orders dependent steps while the UI event loop remains responsive."),
            T("Widgets as immutable descriptions", "A widget is an immutable configuration that describes part of the interface; Flutter rebuilds descriptions when inputs change."),
            T("Stateful lifecycle and rebuilds", "State persists across rebuilds for the same element identity and must release subscriptions or controllers when disposed."),
            T("Packages, project structure, and debugging", "A Flutter project separates source, assets, dependencies, and tests; analyzer and inspector evidence guide debugging."),
        ],
    },
    {
        "path_id": "flutter_development", "code": "FLUT-201", "number": 2,
        "title": "Widgets, Layouts, Navigation and Forms",
        "topics": [
            T("Flutter's constraints layout rule", "Parents pass constraints down, children choose a permitted size, and parents position the resulting boxes."),
            T("Row, Column, Flex, and available space", "Flex layouts divide finite main-axis space by fixed needs and flex factors while cross-axis alignment controls placement."),
            T("Scrolling lists and bounded viewports", "A scrolling viewport needs bounded constraints and should lazily build large sequences to control memory and work."),
            T("Navigation routes as a graph", "Screens are nodes and allowed transitions are directed edges carrying typed arguments and returning optional results."),
            T("Forms, controllers, and validation", "A form collects named values, applies local and cross-field constraints, and submits only a valid snapshot."),
            T("Themes and responsive composition", "Themes encode shared design tokens, while responsive composition selects structures that satisfy current width and content constraints."),
            T("Gestures, hit targets, and feedback", "Gesture handling maps pointer sequences to semantic actions and must provide discoverable, immediate state feedback."),
            T("Accessible widget semantics", "Labels, roles, values, focus order, scalable text, and sufficient targets preserve meaning across assistive input modes."),
        ],
    },
    {
        "path_id": "flutter_development", "code": "FLUT-301", "number": 3,
        "title": "State Management and Application Architecture",
        "topics": [
            T("Local, shared, and derived state", "Place mutable state at the narrowest owner that serves all consumers and compute derived values instead of storing duplicates."),
            T("Explicit state transitions", "Represent each user or system event as an action that transforms a known previous state into one next state."),
            T("Notifiers and observable dependencies", "Observers rebuild only when the values they depend on change; clear subscription ownership prevents leaks and stale views."),
            T("Unidirectional data flow", "State flows down to views and events flow back to an owner, creating a cycle with one authoritative source of truth."),
            T("Repositories and service boundaries", "A repository exposes domain-focused data operations while hiding whether data came from network, database, or cache."),
            T("Dependency injection and test seams", "Dependencies enter through constructors or providers so production implementations can be replaced by controlled test doubles."),
            T("Loading, data, empty, and error states", "Asynchronous screens need an explicit finite state model so no result or failure becomes an accidental null case."),
            T("Layered feature architecture", "Presentation, domain, and data layers point through narrow contracts, limiting the effect of change and simplifying tests."),
        ],
    },
    {
        "path_id": "flutter_development", "code": "FLUT-401", "number": 4,
        "title": "APIs, Local Storage and Offline Applications",
        "topics": [
            T("HTTP clients and typed serialization", "Transport responses become trusted domain values only after status checks, decoding, and field validation."),
            T("Cancellation, timeouts, and stale results", "Asynchronous work needs lifetime rules so obsolete responses cannot overwrite newer screen state."),
            T("Key-value storage and data sensitivity", "Use key-value storage for small preferences, not relational data or secrets that require stronger protection."),
            T("Local databases and schema evolution", "Local tables preserve structured offline state; versioned migrations keep existing installations readable after schema change."),
            T("Cache-aside and freshness decisions", "Read from a cache under an explicit freshness policy, refresh from the source, and define behavior when either side fails."),
            T("Offline queues and conflict resolution", "Queued mutations need stable identities, retry policies, and a deterministic rule for resolving concurrent edits."),
            T("Authentication and secure device storage", "Tokens require protected storage, limited lifetime, redaction, and a clear logout or revocation path."),
            T("Resilient offline-first data flow", "An offline-first feature exposes local state immediately, synchronizes in the background, and communicates pending or conflicted changes."),
        ],
    },
    {
        "path_id": "flutter_development", "code": "FLUT-501", "number": 5,
        "title": "Testing, Performance, Accessibility and Release",
        "topics": [
            T("Unit, widget, and integration tests", "Choose the smallest test boundary that proves the behavior: pure logic, rendered interaction, or multi-screen integration."),
            T("Rebuild measurement and render performance", "Profile frame timing and rebuild scope before changing code; stable inputs and smaller observers reduce unnecessary work."),
            T("Memory, images, and resource lifetime", "Large assets, caches, controllers, and subscriptions consume bounded resources that need sizing and disposal policies."),
            T("Accessibility audits and inclusive flows", "Verify semantics, focus, text scale, contrast, orientation, and error recovery across complete user journeys."),
            T("Internationalization and locale-sensitive data", "Translate messages and format dates, numbers, direction, and plural forms according to locale rather than concatenating fragments."),
            T("Platform permissions and store readiness", "Request the minimum permission at the moment of need and align declared capabilities, privacy notices, and behavior."),
            T("Analytics, privacy, and failure monitoring", "Collect only purposeful events, gain appropriate consent, avoid sensitive fields, and connect failures to actionable context."),
            T("Continuous delivery and staged release", "Automated checks produce signed builds, while staged rollout, monitoring, and rollback control release risk."),
        ],
    },

    # React Native Development
    {
        "path_id": "react_native_development", "code": "RN-101", "number": 1,
        "title": "JavaScript, React and React Native Foundations",
        "topics": [
            T("JavaScript values and mobile input", "External text and device values require explicit type, absence, and range checks before application logic uses them."),
            T("Functions, arrays, and immutable updates", "Pure functions and non-mutating collection operations make state transitions predictable and testable."),
            T("Components and native render trees", "A React Native component maps props and state to native-view descriptions organized as a tree."),
            T("Props and one-way information flow", "Parents pass read-only inputs downward; children communicate events upward through explicit callback contracts."),
            T("State and event transitions", "State records information that affects rendering, and events produce discrete transitions from one valid snapshot to another."),
            T("Core components and platform differences", "Use portable primitives by default and isolate platform-specific behavior behind narrow, tested boundaries."),
            T("Styles, flex layout, and density", "Mobile layout uses flex constraints and logical units so content adapts to screen size, density, and text scale."),
            T("Project structure and debugging evidence", "Separate features, shared components, and services; use logs, inspector state, and minimal reproduction to locate failures."),
        ],
    },
    {
        "path_id": "react_native_development", "code": "RN-201", "number": 2,
        "title": "Components, Navigation, Lists and Forms",
        "topics": [
            T("Component composition and reusable contracts", "Reusable components expose meaningful inputs and events while hiding visual and behavioral implementation details."),
            T("Stack, tab, and modal navigation graphs", "Navigation containers encode different graph relationships; a route should have one clear purpose and typed parameters."),
            T("FlatList virtualization and stable keys", "Virtualized lists render a moving window of items, and stable unique keys preserve item identity across updates."),
            T("Controlled inputs and form state", "Controlled fields derive displayed values from state and emit changes through a single validation-aware transition path."),
            T("Validation and error recovery", "Validation maps field and cross-field constraints to specific, accessible messages without destroying the learner's entered data."),
            T("Responsive styling and safe areas", "Layouts honor available dimensions, text scale, orientation, and system insets rather than assuming fixed coordinates."),
            T("Touch interactions and feedback states", "Press, long-press, swipe, disabled, loading, and success states need distinct rules and immediate perceptible feedback."),
            T("Accessible navigation and forms", "Screen titles, focus movement, labels, hints, errors, and touch targets preserve the task for assistive technologies."),
        ],
    },
    {
        "path_id": "react_native_development", "code": "RN-301", "number": 3,
        "title": "State, Networking and Application Architecture",
        "topics": [
            T("Local state, context, and ownership", "Keep state local until multiple distant consumers need one authority; context distributes values but does not replace a state model."),
            T("Reducers and finite UI states", "A reducer maps state plus action to next state, while finite states prevent impossible loading-data-error combinations."),
            T("Effects, cleanup, and dependency reasoning", "Effects synchronize with external systems and must cancel subscriptions or ignore obsolete results when dependencies change."),
            T("HTTP requests and response validation", "A successful transport status is only one condition; decode and validate response structure before updating trusted state."),
            T("Caching, retries, and server state", "Server-state tools coordinate freshness, deduplication, retries, and invalidation without turning remote data into uncontrolled local copies."),
            T("Service and repository boundaries", "Network and storage details sit behind domain-oriented contracts that views can test without real infrastructure."),
            T("Authentication state and protected routes", "Authentication is an explicit state machine; route access reacts to verified identity without briefly exposing protected content."),
            T("Feature-based application architecture", "Group code by user capability and enforce dependency direction among presentation, domain, and infrastructure concerns."),
        ],
    },
    {
        "path_id": "react_native_development", "code": "RN-401", "number": 4,
        "title": "Device Features, Storage, Security and Offline UX",
        "topics": [
            T("Permission flows and least access", "Explain the user benefit, request only the needed device capability, and provide a usable denied-permission path."),
            T("Camera, media, and resource cleanup", "Device sessions have acquisition, active, paused, and released states; cleanup prevents privacy, battery, and memory problems."),
            T("Local persistence and schema versions", "Choose preference or database storage by data shape and evolve persistent records through tested version migrations."),
            T("Secure storage and secret lifetimes", "Sensitive tokens belong in platform-protected storage, with short lifetime, redacted diagnostics, and explicit revocation."),
            T("Connectivity state and offline feedback", "Connectivity is evidence, not proof of service availability; show cached, pending, failed, and synchronized states explicitly."),
            T("Mutation queues and conflict policies", "Offline writes need unique operation IDs, ordering rules, bounded retries, and deterministic merge or user-resolution behavior."),
            T("Deep links and untrusted external input", "Treat every deep-link parameter as untrusted, validate destination and identity state, and reject unsupported transitions."),
            T("Threat modeling a mobile feature", "Map local assets, device boundaries, network boundaries, entry points, abuse cases, and layered mitigations before implementation."),
        ],
    },
    {
        "path_id": "react_native_development", "code": "RN-501", "number": 5,
        "title": "Performance, Testing and Application Release",
        "topics": [
            T("Unit, component, and device tests", "Match test scope to risk and control time, network, storage, and navigation dependencies for reproducible evidence."),
            T("Render profiling and memoization", "Measure component commits and frame delays; memoization helps only when comparison cost is lower than avoided work."),
            T("Lists, images, and startup performance", "Windowing, correctly sized assets, deferred work, and bundle analysis target the largest measured delays."),
            T("Native bridges and failure boundaries", "Crossing the JavaScript-native boundary has serialization and lifetime costs that need narrow interfaces and error handling."),
            T("Accessibility and international release", "Test screen-reader flow, focus, scaling, contrast, right-to-left layout, and locale formatting on real journeys."),
            T("Privacy declarations and store policies", "Declared data use, permissions, SDK behavior, and in-app consent must describe the same actual system."),
            T("Crash monitoring and release health", "Symbolicated crashes, non-sensitive context, version cohorts, and service indicators reveal whether a release is safe."),
            T("Automated builds and phased rollout", "Repeatable signed builds plus staged exposure, monitoring thresholds, and rollback reduce the impact of release defects."),
        ],
    },

    # Security Fundamentals
    {
        "path_id": "security_fundamentals", "code": "SEC-101", "number": 1,
        "title": "Security Mindset, Risk and the CIA Triad",
        "topics": [
            T("Assets, value, and security objectives", "Security begins by identifying what has value, who depends on it, and which confidentiality, integrity, and availability properties matter."),
            T("Threats, vulnerabilities, and controls", "A threat can exploit a vulnerability; a control prevents, detects, or helps recover from the resulting harm."),
            T("Likelihood, impact, and risk", "Risk priority combines evidence about likelihood and impact instead of treating every weakness as equally urgent."),
            T("Confidentiality decisions", "Confidentiality limits information disclosure through classification, least privilege, secure transport, and controlled sharing."),
            T("Integrity decisions", "Integrity protects authorized and accurate change through validation, permissions, hashes, versioning, and audit evidence."),
            T("Availability and resilience", "Availability uses redundancy, capacity, backups, monitoring, and recovery plans to keep required services usable."),
            T("Trust boundaries and attack surfaces", "A trust boundary marks where assumptions change; every exposed input or capability expands the attack surface that controls must cover."),
            T("Security trade-offs and defense in depth", "Layered controls reduce single points of failure while decisions balance risk reduction, usability, cost, and operational burden."),
        ],
    },
    {
        "path_id": "security_fundamentals", "code": "SEC-201", "number": 2,
        "title": "Operating-System, Network and Protocol Security",
        "topics": [
            T("Accounts, processes, and least privilege", "Separate identities and grant each process only the resources required for its documented task."),
            T("Permissions and secure configuration", "Ownership and access rules should start restrictive, be reviewed against need, and avoid unsafe convenience defaults."),
            T("Patch and vulnerability management", "Inventory systems, assess exposure and impact, test updates, deploy by priority, and verify remediation."),
            T("Network layers and packet journeys", "Data is encapsulated across layers and forwarded hop by hop; each boundary exposes different metadata and control points."),
            T("Addressing, ports, and service exposure", "An address locates a host and a port identifies a service endpoint; exposed listeners must match documented need."),
            T("DNS, TLS, and secure protocol properties", "DNS maps names, while TLS authenticates endpoints and protects transport confidentiality and integrity when validation succeeds."),
            T("Segmentation and firewall decisions", "Segmentation limits paths between trust zones; firewall rules should allow explicit required flows and deny unnecessary reachability."),
            T("Defensive network log analysis", "Correlate timestamps, sources, destinations, actions, and baselines to distinguish expected operations from events requiring investigation."),
        ],
    },
    {
        "path_id": "security_fundamentals", "code": "SEC-301", "number": 3,
        "title": "Web, Application and API Security",
        "topics": [
            T("Application trust boundaries", "Map browser, API, database, third-party, and administrator boundaries so every untrusted transition has validation and authorization."),
            T("Input validation and output encoding", "Validate input for expected shape and encode output for its destination context; the two controls solve different boundary problems."),
            T("Authentication and session defense", "Strong identity proof, protected credentials, expiration, revocation, and anomaly detection reduce account and session risk."),
            T("Authorization and object-level access", "Every protected operation re-evaluates the actor, action, and target object on the server, regardless of interface visibility."),
            T("Secure API contracts and rate controls", "Strict schemas, bounded payloads, consistent errors, quotas, and monitoring limit misuse and accidental overload."),
            T("Browser-origin protections", "Origin policy, safe cookie attributes, CSRF defenses, and content restrictions reduce unintended cross-site actions and script execution."),
            T("Dependency and software-supply-chain risk", "Pin, verify, inventory, scan, minimize, and update dependencies through reviewed and reproducible build steps."),
            T("Threat modeling and remediation planning", "Prioritize feasible abuse paths, select layered controls, assign owners and deadlines, then verify risk reduction."),
        ],
    },
    {
        "path_id": "security_fundamentals", "code": "SEC-401", "number": 4,
        "title": "Cryptography, Identity and Data Protection",
        "topics": [
            T("Cryptographic goals and threat models", "Choose cryptography only after defining the confidentiality, integrity, authenticity, or non-repudiation property and the adversary's capability."),
            T("Hash functions and integrity evidence", "A cryptographic hash maps arbitrary input to a fixed digest with collision and preimage resistance; it does not hide data."),
            T("Symmetric encryption and nonce rules", "Symmetric encryption uses one shared secret, and modern authenticated modes require unique nonces under a key."),
            T("Public-key encryption and signatures", "Public-key systems separate public and private operations; encryption protects secrecy while signatures provide origin and integrity evidence."),
            T("Certificates and trust chains", "A certificate binds an identity to a public key, and validation checks chain, hostname, time, purpose, and revocation evidence."),
            T("Identity lifecycle and multi-factor controls", "Provisioning, authentication, recovery, role change, and deprovisioning form one identity lifecycle with high-risk transitions."),
            T("Data classification and retention", "Classification determines handling, access, encryption, sharing, retention, and verified deletion requirements."),
            T("Key management and cryptographic agility", "Keys need generation, storage, access control, rotation, backup, revocation, and replacement plans independent of application code."),
        ],
    },
    {
        "path_id": "security_fundamentals", "code": "SEC-501", "number": 5,
        "title": "Monitoring, Defensive Operations and Incident Response",
        "topics": [
            T("Security telemetry and log quality", "Useful telemetry has synchronized time, stable identity, event outcome, source context, protected integrity, and bounded sensitive data."),
            T("Baselines, detections, and false positives", "A detection compares observable behavior to a rule or baseline; thresholds balance missed events against investigation cost."),
            T("Triage and evidence preservation", "Triage establishes scope and urgency while recording provenance and preserving original evidence before deeper analysis."),
            T("Incident-response lifecycle", "Preparation, identification, containment, eradication, recovery, and learning form an iterative response process."),
            T("Containment and business trade-offs", "Containment limits ongoing harm but must consider evidence, safety, service dependency, and the possibility of alerting an adversary."),
            T("Recovery and validation", "Recovery restores trusted service in stages and verifies configuration, data integrity, monitoring, and recurrence controls."),
            T("Communication and decision records", "Roles, severity, audience, cadence, known facts, uncertainty, and decisions keep technical and organizational response aligned."),
            T("Post-incident learning and control improvement", "A blameless review connects contributing conditions to owned corrective actions and measurable verification."),
        ],
    },

    # Ethical Hacking (strictly safe/authorized)
    {
        "path_id": "ethical_hacking", "code": "HACK-101", "number": 1,
        "title": "Ethics, Authorization, Scope and Safe Labs",
        "topics": [
            T("Written authorization and legal boundaries", "Testing begins only after a named owner grants written permission for specific systems, dates, methods, and personnel."),
            T("Rules of engagement", "Rules define communication, permitted techniques, stop conditions, data handling, evidence retention, and escalation contacts."),
            T("Scope as explicit sets", "In-scope targets and actions are allowlisted sets; ambiguity, third-party ownership, or missing entries mean stop and clarify."),
            T("Isolated lab architecture", "A safe practice lab uses fictional data, isolated networking, disposable machines, snapshots, and no route to public targets."),
            T("Safety stop conditions", "Unexpected impact, sensitive data, unstable service, scope uncertainty, or lost monitoring triggers an immediate pause and notification."),
            T("Evidence handling and privacy", "Collect the minimum proof, timestamp it, protect integrity, restrict access, and remove it according to the agreed retention rule."),
            T("Risk communication without exaggeration", "Describe observable evidence, realistic preconditions, potential impact, uncertainty, and remediation without claiming unverified compromise."),
            T("Professional conduct and handoff", "Respect scope, minimize disruption, communicate promptly, and transfer findings through approved channels with clear ownership."),
        ],
    },
    {
        "path_id": "ethical_hacking", "code": "HACK-201", "number": 2,
        "title": "Asset Discovery and Reconnaissance Concepts",
        "topics": [
            T("Authorized asset inventory", "Start from owner-provided inventory and record hostname, service, owner, purpose, environment, and scope status for fictional lab assets."),
            T("Passive versus active evidence", "Passive review uses supplied records, while active checks send traffic; the authorization and impact profile differs."),
            T("Service exposure mapping", "Map only approved lab addresses to documented services and compare observed exposure with the intended architecture."),
            T("Metadata and information leakage", "Public or supplied metadata can reveal versions, paths, contacts, or structure; report only evidence within scope and minimize collected personal data."),
            T("Trust-boundary diagrams", "Place assets into zones and draw permitted data flows so unexpected pathways become review questions rather than exploitation attempts."),
            T("Evidence confidence and corroboration", "One signal may be stale or ambiguous; confidence increases when independent approved sources agree."),
            T("Exposure prioritization", "Prioritize externally reachable, sensitive, high-impact, weakly controlled, and owner-unknown assets for defensive review."),
            T("Reconnaissance reporting and remediation", "Turn inventory gaps and unintended exposure into asset ownership, closure, segmentation, and monitoring actions."),
        ],
    },
    {
        "path_id": "ethical_hacking", "code": "HACK-301", "number": 3,
        "title": "Vulnerability Assessment and Safe Validation",
        "topics": [
            T("Finding versus verified vulnerability", "A tool finding is a hypothesis; safe validation confirms affected asset, condition, version, configuration, and evidence without harmful exploitation."),
            T("Scanner scope and safe configuration", "Limit a lab assessment by allowlisted targets, low-impact checks, rate, timing, credentials, exclusions, and stop monitoring."),
            T("False positives and false negatives", "Corroborate results because imperfect detection can report absent weaknesses or miss present ones."),
            T("Version and configuration evidence", "Compare observed approved-lab facts with vendor or policy criteria while accounting for backports and compensating controls."),
            T("Risk rating with context", "Severity combines technical impact, exploit preconditions, exposure, asset value, existing controls, and confidence."),
            T("Minimal proof and non-destructive validation", "Collect the least evidence that demonstrates the condition; do not extract real data, alter state, bypass controls, or establish persistence."),
            T("Remediation selection and verification", "Prefer root-cause fixes, define compensating controls when needed, retest the exact condition, and document residual risk."),
            T("Assessment quality and reproducibility", "A finding records scope, time, environment, method class, evidence, assumptions, impact, fix, and safe retest steps."),
        ],
    },
    {
        "path_id": "ethical_hacking", "code": "HACK-401", "number": 4,
        "title": "Sandbox-Only Web Security Testing",
        "topics": [
            T("Safe web-lab request mapping", "Within the isolated lab, map documented routes, methods, parameters, identity states, and expected responses without probing outside scope."),
            T("Validation review with inert test data", "Use harmless boundary strings and schema cases to verify that the fictional lab accepts only intended shapes and lengths."),
            T("Authorization matrix review", "Build an actor-action-resource matrix and verify allowed and denied outcomes using only provided fictional accounts."),
            T("Session configuration review", "Inspect lab cookie flags, expiration, rotation, logout, and error behavior without attempting credential theft or session hijacking."),
            T("Browser security-header review", "Compare supplied lab headers with the application's resource needs and recommend restrictive, testable policies."),
            T("API error and rate-control review", "Verify that fictional endpoints return consistent non-sensitive errors and bounded responses under approved low-rate tests."),
            T("Dependency and deployment review", "Assess supplied manifests, lockfiles, build settings, and fictional advisories without executing untrusted packages."),
            T("Web finding remediation and retest", "Connect each safe lab observation to root cause, code or configuration control, regression test, and residual-risk statement."),
        ],
    },
    {
        "path_id": "ethical_hacking", "code": "HACK-501", "number": 5,
        "title": "Professional Reporting, Risk Rating and Remediation",
        "topics": [
            T("Executive and technical audiences", "Executives need risk and decisions; technical owners need reproducible evidence, root cause, exact affected scope, and verification criteria."),
            T("Finding anatomy and evidence quality", "A complete finding separates observation, preconditions, impact, likelihood, evidence, affected assets, remediation, and confidence."),
            T("Consistent risk rating", "Use a documented rubric and business context so similar evidence receives comparable priority and uncertainty remains visible."),
            T("Root cause and remediation options", "Distinguish immediate containment, durable correction, compensating control, owner, dependency, cost, and target date."),
            T("Retesting and closure criteria", "Close a finding only when the agreed control is deployed, the original condition no longer holds, regression evidence passes, and residual risk is accepted."),
            T("Metrics without misleading incentives", "Track exposure age, verified closure, recurrence, and coverage rather than rewarding raw finding counts."),
            T("Responsible disclosure and communication", "Use authorized channels, protect details, allow coordinated remediation time, and follow legal and organizational requirements."),
            T("End-to-end assessment portfolio", "A professional portfolio links authorization, scope, methods, evidence, prioritized findings, remediation, retest, and lessons learned."),
        ],
    },

    # Data Structures
    {
        "path_id": "data_structures", "code": "DS-101", "number": 1,
        "title": "Arrays, Strings and Sequential Data",
        "topics": [
            T("Array indices and contiguous sequence models", "An array maps integer positions to ordered values; valid indices form the half-open range from zero to length."),
            T("Traversal and loop invariants", "During left-to-right traversal, define what has been proven about the processed prefix before advancing the boundary."),
            T("Insertion, deletion, and shifting cost", "Changing an array's middle may shift a suffix, so cost grows with the number of displaced elements."),
            T("Strings as sequences", "String algorithms reason about characters or code points, order, boundaries, and often immutable transformations."),
            T("Frequency counting with bounded symbols", "A frequency table maps each allowed symbol to its occurrence count and preserves the invariant that counts sum to processed items."),
            T("Two-dimensional arrays and coordinates", "A grid maps row-column pairs to values; neighbor rules and boundary checks define valid movement."),
            T("Prefix summaries", "A prefix array stores cumulative information so a range query becomes the difference between two boundary summaries."),
            T("Choosing array and string representations", "Choose a representation whose order, access, mutation, memory, and character-handling properties match the operations."),
        ],
    },
    {
        "path_id": "data_structures", "code": "DS-201", "number": 2,
        "title": "Linked Lists, Stacks and Queues",
        "topics": [
            T("Nodes, links, and list invariants", "A linked list is a chain of nodes; each next reference preserves reachability and the tail terminates with no successor."),
            T("Linked-list traversal and search", "Traversal follows links rather than numeric indices and must stop at the end or when the target is found."),
            T("Insertion and deletion by rewiring", "Local list changes update a small set of links, but only after preserving references to the remaining chain."),
            T("Fast and slow pointer reasoning", "Pointers moving at different rates reveal middle positions or cycles through relative-distance invariants."),
            T("Stacks and last-in-first-out", "A stack exposes only the most recently added unremoved item, supporting nested and reversal processes."),
            T("Queues and first-in-first-out", "A queue removes items in arrival order and needs separate front and rear state for efficient operations."),
            T("Deques and monotonic queues", "A deque supports both ends; a monotonic deque discards dominated candidates while preserving useful order."),
            T("Selecting linear structures", "Choose arrays, lists, stacks, queues, or deques from required access position, update pattern, order, and complexity."),
        ],
    },
    {
        "path_id": "data_structures", "code": "DS-301", "number": 3,
        "title": "Hash Maps, Hash Sets and Frequency Structures",
        "topics": [
            T("Key-value and membership models", "A map associates unique keys with values, while a set records only whether a key is present."),
            T("Hash functions and bucket placement", "A hash function deterministically maps a key to a numeric code used to select a bounded bucket."),
            T("Collisions and equality", "Different keys can share a bucket, so collision handling must still use correct key equality to distinguish them."),
            T("Load factor and resizing", "As entries per bucket rise, expected operation cost worsens; resizing expands capacity and redistributes entries."),
            T("Frequency maps and counting invariants", "After processing a prefix, each stored value equals the exact number of times its key appeared in that prefix."),
            T("Grouping and indexing by derived keys", "A derived canonical key can group records that share a property, such as normalized letters or category."),
            T("Memoization and cached subproblems", "Memoization maps a complete subproblem state to its solved result, avoiding repeated work without changing correctness."),
            T("Hash-structure trade-offs", "Expected constant-time lookup depends on good hashing, while ordering, worst-case needs, memory, and key mutability may favor another structure."),
        ],
    },
    {
        "path_id": "data_structures", "code": "DS-401", "number": 4,
        "title": "Trees, Binary Search Trees and Heaps",
        "topics": [
            T("Tree vocabulary and recursive structure", "A tree has one root and unique parent paths; every subtree is itself a tree with smaller scope."),
            T("Depth-first and breadth-first traversal", "Depth-first traversal follows a branch before siblings, while breadth-first traversal processes nodes by distance from the root."),
            T("Binary search tree invariant", "Every node partitions keys so left-subtree values precede it and right-subtree values follow it under the chosen ordering rule."),
            T("BST search, insertion, and deletion", "Operations follow the ordering invariant; deletion reconnects subtrees while preserving every remaining key's order."),
            T("Balanced height and logarithmic paths", "Keeping subtree heights controlled prevents an ordered tree from degenerating into a linear chain."),
            T("Heap order and complete shape", "A binary heap combines complete-tree shape with parent priority, guaranteeing fast access to one extreme rather than full order."),
            T("Priority queues and top-k reasoning", "A priority queue repeatedly exposes the highest- or lowest-priority item; a bounded heap can retain the best k candidates."),
            T("Choosing hierarchical structures", "Select a tree, BST, heap, or flat structure according to hierarchy, ordered lookup, priority access, update cost, and memory."),
        ],
    },
    {
        "path_id": "data_structures", "code": "DS-501", "number": 5,
        "title": "Graphs, Tries and Advanced Structures",
        "topics": [
            T("Graph vertices, edges, and representations", "A graph models entities and relationships; adjacency lists favor sparse edges while matrices favor constant-time edge checks."),
            T("Graph traversal and visited invariants", "BFS or DFS expands reachable vertices while a visited set ensures each vertex is finalized according to the traversal rule."),
            T("Shortest paths in unweighted graphs", "BFS discovers vertices in nondecreasing edge distance, so the first discovery gives a shortest unweighted path."),
            T("Directed acyclic graphs and topological order", "A topological order places every directed prerequisite before its dependent and exists only when there is no directed cycle."),
            T("Weighted paths and relaxation", "Relaxation improves a best-known distance when an edge offers a cheaper route; algorithm choice depends on weight properties."),
            T("Disjoint sets and connectivity", "Union-find maintains partitions under union and connectivity queries using representative parents, path compression, and rank or size."),
            T("Tries and prefix structure", "A trie shares prefixes along root-to-node paths, trading memory for operations proportional to key length."),
            T("Advanced structure selection", "Choose representations by operation mix, density, ordering, connectivity, prefix needs, guarantees, and implementation cost."),
        ],
    },

    # Algorithms and Coding Interviews
    {
        "path_id": "algorithms_coding_interviews", "code": "AL-101", "number": 1,
        "title": "Complexity, Searching and Sorting",
        "topics": [
            T("Input size and operation counting", "Define input size, identify the repeated primitive operation, and express how its count grows as input scales."),
            T("Time and space complexity classes", "Asymptotic bounds compare growth while ignoring constant factors, but auxiliary memory and real constraints still affect choice."),
            T("Linear search and early termination", "Linear search preserves that the target is absent from the processed prefix and stops on discovery or exhaustion."),
            T("Binary search and boundary invariants", "Binary search maintains a sorted candidate interval containing every possible answer and removes a proven half each step."),
            T("Stable comparison sorting", "A stable sort preserves the input order of equal keys, which matters when records have earlier ordering decisions."),
            T("Divide-and-conquer sorting", "Merge sort divides, solves smaller arrays, and merges sorted sequences; quicksort partitions around a pivot with data-dependent balance."),
            T("Non-comparison sorting constraints", "Counting or bucket methods exploit bounded key structure to avoid comparison lower bounds at a memory cost."),
            T("Selecting and explaining an algorithm", "Choose from input properties, operation costs, memory, stability, worst-case guarantees, and implementation risk, then justify the trade-off."),
        ],
    },
    {
        "path_id": "algorithms_coding_interviews", "code": "AL-201", "number": 2,
        "title": "Two Pointers, Sliding Windows and Prefix Structures",
        "topics": [
            T("Opposite-direction two pointers", "On ordered data, pointer movement discards a region proven unable to contain a solution."),
            T("Same-direction read and write pointers", "A read pointer inspects each item while a write pointer marks the boundary of the valid compacted prefix."),
            T("Fixed-size sliding windows", "Update a fixed window by adding the entering item and removing the leaving item instead of recomputing the aggregate."),
            T("Variable windows with monotonic constraints", "Expand to gain candidates and shrink while invalid, provided the constraint changes monotonically with window boundaries."),
            T("Prefix sums and range queries", "Cumulative boundaries convert an interval sum into one subtraction after linear preprocessing."),
            T("Prefix frequencies and balance states", "Equal prefix states imply that the segment between them has zero net change under the tracked balance."),
            T("Monotonic stacks and next-boundary problems", "A monotonic stack keeps unresolved candidates in order and removes those resolved by the current value."),
            T("Pattern selection and counterexamples", "Pointer and window methods require order or monotonicity; construct counterexamples before applying them to arbitrary constraints."),
        ],
    },
    {
        "path_id": "algorithms_coding_interviews", "code": "AL-301", "number": 3,
        "title": "Recursion, Backtracking and Greedy Reasoning",
        "topics": [
            T("Recursive contracts and base cases", "A recursive function solves one state by reducing it to smaller states and needs base cases that cover every terminating path."),
            T("Call stacks and recurrence traces", "Each call owns parameters and local state; the call tree reveals repeated work and maximum stack depth."),
            T("Backtracking state and undo", "Choose, explore, and undo so every branch starts from the same valid prefix state."),
            T("Pruning invalid and dominated branches", "Pruning is correct only when a predicate proves that no completion of the current partial state can improve or satisfy the answer."),
            T("Permutations, combinations, and duplicates", "State representation and start boundaries determine whether order matters and whether equal choices create duplicate solutions."),
            T("Greedy choice properties", "A greedy method is valid when a locally preferred choice can be exchanged into some optimal solution without reducing quality."),
            T("Interval and scheduling decisions", "Sorting by the right boundary can expose an exchange argument for maximizing compatible choices in specific interval problems."),
            T("Proving or rejecting greedy solutions", "Use exchange proofs, stays-ahead invariants, and small counterexamples rather than trusting locally attractive choices."),
        ],
    },
    {
        "path_id": "algorithms_coding_interviews", "code": "AL-401", "number": 4,
        "title": "Dynamic Programming and Optimization",
        "topics": [
            T("Optimal substructure and overlapping states", "Dynamic programming applies when optimal solutions combine optimal subproblem results and the same states recur."),
            T("State definition and sufficient information", "A DP state must contain exactly the information needed to evaluate future choices without remembering the entire history."),
            T("Transitions and dependency graphs", "A transition combines already solved predecessor states, forming an acyclic dependency graph or a controlled iterative process."),
            T("Memoization and tabulation", "Memoization explores needed states top-down; tabulation orders all relevant states bottom-up according to dependencies."),
            T("One-dimensional sequence DP", "Sequence states often represent the best answer for a prefix or endpoint, with transitions considering the final decision."),
            T("Grid and path DP", "Grid states aggregate valid predecessor paths or costs while boundaries encode unreachable or base positions."),
            T("Knapsack-style choice DP", "Choice states track an item boundary and limited resource; iteration direction determines whether an item may be reused."),
            T("Space optimization and correctness proof", "Discard old DP layers only after proving no future transition depends on them, and state the invariant for the compressed array."),
        ],
    },
    {
        "path_id": "algorithms_coding_interviews", "code": "AL-501", "number": 5,
        "title": "Mixed Problems, Interview Strategy and Communication",
        "topics": [
            T("Clarifying ambiguous problem statements", "Restate the input-output contract, constraints, examples, edge cases, and allowed assumptions before choosing a method."),
            T("From brute force to bottleneck", "Start with a correct baseline, locate the operation causing excessive growth, and replace it using structure or precomputation."),
            T("Selecting mixed patterns", "Classify order, locality, repetition, hierarchy, connectivity, and optimization structure before selecting a pattern."),
            T("Correctness explanations with invariants", "Explain initialization, preservation, termination, and why the invariant implies the required result."),
            T("Complexity under realistic constraints", "Relate time, space, recursion depth, numeric range, and input distribution to actual limits instead of naming Big-O alone."),
            T("Testing strategy and adversarial cases", "Cover empty, minimal, maximal, duplicate, ordered, disconnected, overflow, and constraint-boundary cases relevant to the contract."),
            T("Communicating while coding", "Narrate decisions, name invariants, check intermediate states, and respond to feedback without abandoning the proven contract."),
            T("Debugging and post-solution refinement", "Trace the first divergent state, repair the cause, rerun targeted tests, then discuss alternatives and trade-offs."),
        ],
    },

    # Machine Learning Fundamentals
    {
        "path_id": "machine_learning_fundamentals", "code": "ML-101", "number": 1,
        "title": "Python Data and Mathematical Foundations",
        "topics": [
            T("Examples, features, labels, and matrices", "Represent n examples with d numeric features as an n-by-d matrix and align each supervised target with exactly one row."),
            T("Vectors, dot products, and similarity", "A dot product combines aligned components into a weighted sum; magnitude and angle affect how it should be interpreted."),
            T("Functions and model mappings", "A model is a parameterized function that maps an input vector to a prediction with a documented output meaning."),
            T("Summary statistics and distributions", "Center, spread, quantiles, and shape describe different distribution properties and can reveal outliers or skew."),
            T("Scaling and normalization", "Rescaling changes feature geometry and optimization behavior; fit transformation parameters only on training data."),
            T("Missing values and data validity", "Absence can be informative or accidental; document its mechanism, choose a treatment, and preserve an indicator when needed."),
            T("Dataset splits and leakage prevention", "Training, validation, and test sets serve different decisions, and no future or target-derived information may cross backward."),
            T("Reproducible data pipelines", "Version data, code, parameters, random seeds, and environment so the same inputs produce traceable outputs."),
        ],
    },
    {
        "path_id": "machine_learning_fundamentals", "code": "ML-201", "number": 2,
        "title": "Supervised and Unsupervised Learning",
        "topics": [
            T("Regression as numeric prediction", "Regression maps features to a continuous value and is evaluated against the size and meaning of numeric errors."),
            T("Classification and decision boundaries", "Classification estimates class evidence or probability and applies a threshold or decision rule tied to error costs."),
            T("Linear models and weighted features", "A linear model combines features through weights and an intercept, creating an interpretable flat decision surface."),
            T("Tree-based partitioning", "A decision tree recursively partitions feature space by rules that improve target separation while risking overfit when too deep."),
            T("Nearest-neighbor reasoning", "Nearest-neighbor methods predict from nearby training examples under a chosen distance and scaling, with storage and query costs."),
            T("Clustering and unsupervised objectives", "Clustering groups examples by an explicit similarity objective, but groups do not automatically equal meaningful real-world categories."),
            T("Train, fit, predict, and transform", "Fitting learns parameters from training data; prediction applies the learned mapping, while transformation changes representations."),
            T("Model assumptions and baseline comparisons", "A simple baseline exposes whether a model adds useful signal and which assumptions fail on important subgroups or ranges."),
        ],
    },
    {
        "path_id": "machine_learning_fundamentals", "code": "ML-301", "number": 3,
        "title": "Features, Evaluation, Bias and Model Selection",
        "topics": [
            T("Feature engineering and valid information", "Create features from information available at prediction time and document their meaning, units, and failure cases."),
            T("Confusion matrices", "A confusion matrix counts actual-versus-predicted classes and is the source for precision, recall, specificity, and related metrics."),
            T("Thresholds and asymmetric error costs", "Changing a score threshold trades false positives against false negatives; choose it from operational costs and capacity."),
            T("Regression metrics and scale", "MAE, squared-error measures, and relative metrics weight errors differently and must be interpreted in target units and distribution."),
            T("Cross-validation and model selection", "Use validation folds to estimate choice performance while keeping the final test set untouched until decisions are complete."),
            T("Underfitting, overfitting, and regularization", "Compare training and validation behavior; regularization constrains flexibility to improve generalization rather than training fit."),
            T("Bias, subgroup evaluation, and uncertainty", "Aggregate performance can hide unequal errors; evaluate meaningful groups with sample sizes and uncertainty visible."),
            T("Experiment tracking and honest conclusions", "Record hypotheses, configurations, metrics, seeds, exclusions, and negative results before drawing bounded conclusions."),
        ],
    },
    {
        "path_id": "machine_learning_fundamentals", "code": "ML-401", "number": 4,
        "title": "Neural Networks and Deep Learning Foundations",
        "topics": [
            T("Neurons, layers, and tensor shapes", "A layer maps an input tensor shape to an output shape using learned parameters; shape compatibility is a structural invariant."),
            T("Activations and nonlinear functions", "Nonlinear activations allow stacked layers to represent more than one linear transformation, while saturation affects gradients."),
            T("Loss functions and learning objectives", "A loss converts prediction error into a scalar training signal and must match output meaning, data distribution, and error costs."),
            T("Gradients and backpropagation", "Backpropagation applies the chain rule through the computation graph to assign each parameter its contribution to loss change."),
            T("Gradient descent and learning rates", "An optimizer updates parameters opposite the estimated gradient; step size balances slow progress against instability."),
            T("Batches, epochs, and stochastic estimates", "A batch estimates the full-data gradient, an epoch processes the training set, and shuffling changes correlation in updates."),
            T("Regularization and generalization", "Weight penalties, data augmentation, dropout, and early stopping constrain effective capacity in different ways."),
            T("Training diagnostics and failure modes", "Learning curves, gradient norms, data checks, and baseline comparisons distinguish optimization, representation, leakage, and overfit problems."),
        ],
    },
    {
        "path_id": "machine_learning_fundamentals", "code": "ML-501", "number": 5,
        "title": "Production ML, Monitoring and Responsible AI",
        "topics": [
            T("Training-serving consistency", "Production preprocessing and feature definitions must match training exactly or predictions operate on a different input space."),
            T("Model packaging and inference contracts", "A deployable model specifies version, feature schema, output semantics, latency, resource limits, and failure behavior."),
            T("Data drift and performance monitoring", "Monitor input and prediction distributions continuously, but confirm quality drift with delayed ground truth when available."),
            T("Feedback loops and delayed labels", "Model decisions can change future data; evaluation must account for selection effects, missing outcomes, and label delay."),
            T("Safe rollout and rollback", "Shadow, canary, or staged deployment limits exposure while predefined metrics and rollback criteria control risk."),
            T("Fairness, privacy, and human oversight", "Evaluate affected groups, minimize data, protect sensitive attributes, define appeal, and assign humans meaningful decision authority."),
            T("Model cards and decision documentation", "Document purpose, data, metrics, limitations, ethical considerations, owners, and prohibited uses for accountable deployment."),
            T("Incident response for ML systems", "Detect harmful behavior, contain model or data changes, preserve evidence, restore a safe baseline, and update controls from lessons learned."),
        ],
    },

    # NLP and AI
    {
        "path_id": "nlp_ai", "code": "AI-101", "number": 1,
        "title": "Text Processing, Tokens and Numerical Representation",
        "topics": [
            T("Text units, Unicode, and normalization", "Text is encoded as Unicode sequences; normalization choices can merge visually equivalent forms while case and punctuation may carry meaning."),
            T("Tokenization and vocabulary boundaries", "A tokenizer maps text to token IDs under a fixed vocabulary, and different segmentations change sequence length and information sharing."),
            T("Bag-of-words vectors", "A bag-of-words vector records token counts or presence while discarding order, producing a sparse document-feature matrix."),
            T("TF-IDF weighting", "TF-IDF raises terms frequent in one document but rare across the collection, with smoothing and normalization affecting scale."),
            T("N-grams and local order", "Word or character n-grams retain bounded local order at the cost of a much larger feature space."),
            T("Text cleaning without destroying signal", "Every cleaning step encodes an assumption; validate whether punctuation, casing, numbers, dialect, or spelling are useful for the task."),
            T("Sequence padding, masks, and lengths", "Batches align variable sequences using padding, while masks ensure padded positions do not affect computation or evaluation."),
            T("Text data pipelines and leakage", "Split by the real deployment unit before fitting vocabulary or statistics, and track source, consent, duplicates, and labels."),
        ],
    },
    {
        "path_id": "nlp_ai", "code": "AI-201", "number": 2,
        "title": "Text Classification, Embeddings and Similarity",
        "topics": [
            T("Text classification contracts", "Define allowed inputs, label meaning, multi-class or multi-label structure, uncertainty, and the operational action triggered by a prediction."),
            T("Sparse linear text classifiers", "Linear classifiers weight token features, creating a transparent baseline that often performs strongly on limited labeled data."),
            T("Dense embeddings and vector geometry", "An embedding maps an item to a dense vector where distance or angle is intended to reflect selected relationships."),
            T("Cosine similarity", "Cosine similarity compares vector direction rather than magnitude, but meaningful interpretation still depends on how the embeddings were trained."),
            T("Nearest-neighbor semantic retrieval", "Embed a query and candidates under the same model, retrieve nearby vectors, then validate relevance with task-specific labels."),
            T("Class imbalance and threshold choice", "Imbalanced labels require per-class metrics, suitable sampling or weighting, and thresholds tied to error costs."),
            T("Embedding bias and representation limits", "Vector neighborhoods can reproduce training associations and underrepresent languages, dialects, or domains."),
            T("Evaluation sets and error analysis", "Stratify errors by class, language form, length, ambiguity, and subgroup to turn metric gaps into model or data actions."),
        ],
    },
    {
        "path_id": "nlp_ai", "code": "AI-301", "number": 3,
        "title": "Sequence Models, Attention and Transformers",
        "topics": [
            T("Sequence state and recurrent models", "A recurrent model updates a hidden state from the current token and previous state, compressing prefix information through time."),
            T("Long-range dependencies and gradient paths", "Long sequences create repeated transformations that can weaken or amplify gradients and overload a fixed hidden state."),
            T("Attention as weighted aggregation", "Attention computes query-key compatibility, normalizes weights, and returns a weighted sum of value vectors."),
            T("Self-attention tensor shapes", "Each sequence position produces queries, keys, and values; pairwise scores create a sequence-by-sequence relationship matrix."),
            T("Position information", "Because attention alone is insensitive to token order, positional features inject absolute or relative sequence relationships."),
            T("Transformer blocks and residual paths", "Attention and feed-forward transformations are wrapped with residual connections and normalization to preserve information and trainability."),
            T("Causal and padding masks", "A causal mask blocks future positions, while a padding mask blocks artificial batch padding; they encode different constraints."),
            T("Pretraining, fine-tuning, and limitations", "Pretraining learns broad statistical representations; adaptation changes task behavior but does not guarantee truth, fairness, or domain coverage."),
        ],
    },
    {
        "path_id": "nlp_ai", "code": "AI-401", "number": 4,
        "title": "LLM Applications, Retrieval and Structured Generation",
        "topics": [
            T("Prompt contracts and bounded tasks", "A reliable prompt states role, input boundaries, required output schema, uncertainty behavior, and prohibited actions."),
            T("Structured output and schema validation", "Generated text becomes application data only after parsing, schema validation, and safe handling of missing or extra fields."),
            T("Retrieval pipelines", "A retrieval system chunks approved sources, indexes representations, retrieves candidates, and supplies traceable context for generation."),
            T("Chunking, ranking, and context budgets", "Chunk boundaries trade completeness against specificity, while reranking and token budgets determine which evidence reaches the model."),
            T("Grounding and citation verification", "A grounded answer must be supported by retrieved evidence, and citation checks must verify that the cited passage entails the claim."),
            T("Tool use and permission boundaries", "Treat model-proposed actions as untrusted plans; validate arguments, permissions, target identity, side effects, and confirmation needs."),
            T("Conversation state and memory", "Store only purposeful, consented facts with provenance, lifetime, user controls, and separation between instructions and retrieved content."),
            T("Failure modes and resilient application design", "Handle hallucination, prompt injection, missing evidence, latency, refusal, tool error, and partial output as explicit states."),
        ],
    },
    {
        "path_id": "nlp_ai", "code": "AI-501", "number": 5,
        "title": "Evaluation, Safety, Bias and Production NLP Systems",
        "topics": [
            T("Task-specific evaluation design", "Define representative inputs, reference criteria, scoring rules, slices, and acceptance thresholds before optimizing a language system."),
            T("Human evaluation and rubric reliability", "Train evaluators on anchored rubrics, use blind comparisons, measure agreement, and adjudicate ambiguous cases."),
            T("Factuality and groundedness measurement", "Separate claim correctness, evidence support, citation accuracy, completeness, and calibrated uncertainty."),
            T("Safety threat models and red teaming", "Identify users, assets, misuse cases, failure severity, safeguards, and residual risk; test only in authorized controlled environments."),
            T("Bias and multilingual evaluation", "Evaluate dialects, languages, identities, and culturally dependent meanings with appropriate reviewers and sample-size uncertainty."),
            T("Privacy and sensitive-data controls", "Minimize collection, detect and redact sensitive data, constrain retention, isolate access, and test memorization or disclosure risks."),
            T("Production monitoring and change control", "Track quality, safety, latency, cost, retrieval health, model versions, and prompt versions with staged changes and rollback."),
            T("Responsible launch and incident response", "Launch only with owners, user disclosure, feedback and appeal paths, escalation, containment, recovery, and documented limitations."),
        ],
    },
]


assert len(TRACKS) == 5
assert len(PATHS) == 10
assert len(LEVELS) == 50
assert all(len(level["topics"]) == 8 for level in LEVELS)

